name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [17.9.0]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Deploy to private server
        run: |
          ssh oracle@10.27.1.83 'cd /u01/software/nodejs/p2p_node/P2P_Node && git pull && npm install && npm start'
