interface NameDescriptionLookup {
  [name: string]: string;
}

// Define the lookup table
export const columnNameDescriptionLookup: NameDescriptionLookup = {
  XXP2P_SUPPLIER_SITE_ID: "Supplier Site Id",
  XXP2P_SUPPLIER_SITE_SUPPLIER_ID: "Supplier Id In Site",
  XXP2P_SUPPLIER_SITE_COUNTRY: "Site Country",
  XXP2P_SUPPLIER_SITE_ADDRESS_LINE1: "Site Name",
  XXP2P_SUPPLIER_SITE_ADDRESS_LINE2: "Site Address",
  XXP2P_SUPPLIER_SITE_CITY_STATE: "Site City",
  XXP2P_SUPPLIER_SITE_ZIP_CODE: "Site ZIP Code",
  XXP2P_SUPPLIER_SITE_EMAIL: "Supplier Email In Site",
  XXP2P_SUPPLIER_SITE_MOBILE_NUMBER: "Supplier Mobile No In Site",
  XXP2P_SUPPLIER_SITE_USER_ID: "User Id In Site",
  XXP2P_SUPPLIER_SITE_ACTIVE_STATUS: "Site Active Status",
  XXP2P_SUPPLIER_SITE_RFQ: "RFQ In Site",
  XXP2P_SUPPLIER_SITE_PAYABLE: "Payable In Site",
  XXP2P_SUPPLIER_SITE_PURCHASING: "Purchasing In Site",
  // Add more names and descriptions as needed
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_ID: "Id In Documents Step-1",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_USER_ID: "User Id In Documents Step-1",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_SUPPLIER_ID:
    "Supplier Id In Documents Step-1",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_TRADE_OR_EXPORT_LICENSE_NUMBER:
    "Trade License/ Export License number",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_TRADE_OR_EXPORT_LICENSE_START_DATE:
    "Trade License/ Export License Start date",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_TRADE_OR_EXPORT_LICENSE_END_DATE:
    "Trade License/ Export License End date",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_TRADE_OR_EXPORT_LICENSE_FILE_NAME:
    "Trade License/ Export License File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_TRADE_OR_EXPORT_LICENSE_ORIGINAL_FILE_NAME:
    "Trade License/ Export License Original File name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_ETIN_NUMBER: "E-TIN Number",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_ETIN_FILE_NAME:
    "E-TIN Number File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_ETIN_ORG_FILE_NAME:
    "E-TIN Number Original File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_EBIN_NUMBER: "E-BIN Number",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_EBIN_FILE_NAME:
    "E-BIN Number File name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_EBIN_ORG_FILE_NAME:
    "E-BIN Number Original File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_TAX_RTN_ASSMNT_YEAR:
    "Tax Return Assessment Year",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_TAX_RTN_ACKN_SLIP_FILE_NAME:
    "Tax Return Acknowledgement Slip file Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_TAX_RTN_ACKN_SLIP_ORIGINAL_FILE_NAME:
    "Tax Return Acknowledgement Slip Original file Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_INCORPORATION_NUMBER:
    "Incorporation Number",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_INCORPORATION_CIRTIFICATE_FILE_NAME: "",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_INCORPORATION_CIRTIFICATE_ORIGINAL_FILE_NAME:
    "Certificate of Incorporation File name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_MEMORANDUM_ASSOCIATION_FILE_NAME:
    "Certificate of Incorporation Original File name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_MEMORANDUM_ASSOCIATION_ORIGINAL_FILE_NAME:
    "Memorandum of Association Original File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_AUTHORIZED_SIGNS_FILE_NAME:
    "List of Authorized Signatories File name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_AUTHORIZED_SIGNS_ORIGINAL_FILE_NAME:
    "List of Authorized Signatories Original File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_ARTICLE_ASSOCIATION_FILE_NAME:
    "Articles of Association File name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_ARTICLE_ASSOCIATION_ORIGINAL_FILE_NAME:
    "Articles of Association Original File name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_PROMINENT_CLIENTS_FILE_NAME:
    "List of Prominent Clients File name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_PROMINENT_CLIENTS_ORIGINAL_FILE_NAME:
    "List of Prominent Clients Original File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_GOODS_LIST_FILE_NAME:
    "List of Available Goods / Services File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_GOODS_LIST_ORG_FILE_NAME:
    "List of Available Goods / Services Original File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_COMPANY_BANK_SOLVENCY_CIRTIFICATE_FILE_NAME:
    "Company Solvency Certificate / Bank Certificate File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_COMPANY_BANK_SOLVENCY_CIRTIFICATE_ORIGINAL_FILE_NAME:
    "Company Solvency Certificate / Bank Certificate original File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_EXCELLENCY_SPECIALIED_CIRTIFICATE_FILE_NAME:
    "Certificates of Excellency, Specializations etc File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_EXCELLENCY_SPECIALIED_CIRTIFICATE_ORIGINAL_FILE_NAME:
    "Certificates of Excellency, Specializations etc Original File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_RECOMMENDATION_CIRTIFICATE_FILE_NAME:
    "Recommendation / Performance Certificate File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_RECOMMENDATION_CIRTIFICATE_ORIGINAL_FILE_NAME:
    "Recommendation / Performance Certificate Original File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_COMPANY_PROFILE_FILE_NAME:
    "Company Profile File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_COMPANY_PROFILE_ORIGINAL_FILE_NAME:
    "Company Profile Original File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_QA_CIRTIFICATE_FILE_NAME:
    "Quality Assurance Certificate File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_QA_CIRTIFICATE_ORIGINAL_FILE_NAME:
    "Quality Assurance Certificate Original File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_ANNUAL_TURNOVER_FILE_NAME:
    "Annual Turnover(Non-BD) File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_ANNUAL_TURNOVER_ORIGINAL_FILE_NAME:
    "Annual Turnover(Non-BD) Original File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_MACHINE_MANPOWER_LIST_FILE_NAME:
    "List of Machineries, Manpower, Competencies File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_MACHINE_MANPOWER_LIST_ORIGINAL_FILE_NAME:
    "List of Machineries, Manpower, Competencies Original File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_BUSINESS_PREMISES_FILE_NAME:
    "Business Premises (rented / owned, with address) File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_BUSINESS_PREMISES_ORIGINAL_FILE_NAME:
    "Business Premises (rented / owned, with address) original File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_PROFILE_PIC1_FILE_NAME:
    "Photograph of Owner-1 File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_PROFILE_PIC1_ORIGINAL_FILE_NAME:
    "Photograph of Owner-1 Original File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_PROFILE_PIC2_FILE_NAME:
    "Photograph of Owner-2 File Name",
  XXP2P_SUPPLIER_REGISTRATION_DOCUMENTS_PROFILE_PIC2_ORIGINAL_FILE_NAME:
    "Photograph of Owner-2 Original File Name",

  XXP2P_SUPPLIER_BANK_ID: "Bank Id",
  XXP2P_SUPPLIER_BANK_SUPPLIER_ID: "Supplier Id In Bank",
  XXP2P_SUPPLIER_BANK_ACCOUNT_NAME: "Account Name",
  XXP2P_SUPPLIER_BANK_ACCOUNT_NUMBER: "Account Number",
  XXP2P_SUPPLIER_BANK_BANK_NAME: "Bank Name",
  XXP2P_SUPPLIER_BANK_BRANCH_NAME: "Bank Branch Name",
  XXP2P_SUPPLIER_BANK_ROUTING_SWIFT_CODE: "Bank Routing Code",
  XXP2P_SUPPLIER_BANK_SITE_ID: "Site Id In Bank",
  XXP2P_SUPPLIER_BANK_CHEQUE_FILE_NAME: "Bank Cheque File Name",
  XXP2P_SUPPLIER_BANK_CHEQUE_FILE_ORIGINAL_NAME:
    "Original Bank Cheque File Name",
  XXP2P_SUPPLIER_BANK_USER_ID: "User Id In Bank",
  XXP2P_SUPPLIER_BANK_ACTIVE_STATUS: "Bank Active Status",
  XXP2P_SUPPLIER_BANK_BANK_PARTY_ID: "Bank party Id",
  XXP2P_SUPPLIER_BANK_BRANCH_PARTY_ID: "Branch party Id",
  XXP2P_SUPPLIER_BANK_CURRENCY_CODE: "Currency Code",
  XXP2P_SUPPLIER_BANK_MULTI_CURRENCY_ALLOWED_FLAG:
    "Multi Currency Allowed Flag",
  XXP2P_SUPPLIER_BANK_PAYMENT_MULTI_CURRENCY_FLAG:
    "Payment Multi Currency Flag",
  XXP2P_SUPPLIER_BANK_SWIFT_CODE: "Swift Code",

  XXP2P_SUPPLIER_BSC_INFO_USER_ID: "User Id In Basic Info",
  XXP2P_SUPPLIER_BSC_INFO_SUPPLIER_ID: "Supplier Id In Basic Info",
  XXP2P_SUPPLIER_BSC_INFO_ORGANIZATION_NAME: "Organization Name In Basic Info",
  XXP2P_SUPPLIER_BSC_INFO_SUPPLIER_ADDRESS: "Supplier Address In Basic Info",
  XXP2P_SUPPLIER_BSC_INFO_INCORPORATE_IN: "Incorporate In Basic Info",
  XXP2P_SUPPLIER_BSC_INFO_CATEGORY_ID: "Category Id In Basic Info",
  XXP2P_SUPPLIER_BSC_INFO_COUNTRY: "Country",
  XXP2P_SUPPLIER_BSC_INFO_ORGANIZATION_TYPE: "Organization Type In Basic Info",
  XXP2P_SUPPLIER_BSC_INFO_ITEM_CATEGORY: "Item Category In Basic Info",
  XXP2P_SUPPLIER_BSC_INFO_ID: "Id In Basic Info",

  XXP2P_SUPPLIER_SITE_BANKS_USER_ID: "User Id In Site's Bank",
  XXP2P_SUPPLIER_SITE_BANKS_SITE_ID: "Site Id In Site's Bank",
  XXP2P_SUPPLIER_SITE_BANKS_BANK_ID: "Bank Id In Site's Bank",
  XXP2P_SUPPLIER_SITE_BANKS_ACTIVE_STATUS: "Bank Active Status In Site's Bank",
  XXP2P_SUPPLIER_SITE_BANKS_ID: "Id In Site's Bank",

  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_ID: "Id In Contact",
  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_SUPPLIER_ID: "Supplier Id In Contact",
  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_NAME: "Contact Person Name",
  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_POSITION: "Contact Person Position",
  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_MOB_NUMBER_1:
    "Contact Person Mobile Number 1",
  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_EMAIL: "Contact Person Email Address",
  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_NID_PASSPORT_NUMBER:
    "Contact Person NID or Passport",
  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_IS_NID: "Is NID Selected",
  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_NID_PASSPORT_FILE_NAME:
    "Contact Person NID or Passport File Name",
  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_SIGNATURE_ORIGINAL_FILE_NAME:
    "Contact Person Signature Original File Name",
  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_SIGNATURE_FILE_NAME:
    "Contact Person Signature File Name",
  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_NID_PASSPORT_ORIGINAL_FILE_NAME:
    "NID or Passport original File Name",
  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_IS_AGENT: "Agent or Not",
  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_CREATED_BY: "Contact Person Created By",
  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_CREATION_DATE:
    "Contact Person Creation Date",
  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_LAST_UPDATED_BY:
    "Contact Person Last Updated By",
  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_LAST_UPDATE_DATE:
    "Contact Person Last Update Date",
  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_MOB_NUMBER_2:
    "Contact Person Mobile Number 2",
  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_USER_ID: "Contact Person User Id",
  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_TITLE: "Contact Person Title",
  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_MIDDLE_NAME: "Contact Person Middle Name",
  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_LAST_NAME: "Contact Person Last Name",
  XXP2P_SUPPLIER_CONTACT_PERSON_DTLS_FIRST_NAME: "Contact Person First Name",

  XXP2P_SUPPLIER_AGENT_DTLS_SUPPLIER_CONTACT_PERSON_ID:
    "Contact Person Id In Agent",
  XXP2P_SUPPLIER_AGENT_DTLS_SUPPLIER_ID: "Supplier Id In Agent",
  XXP2P_SUPPLIER_AGENT_DTLS_AGENT_NAME: "Agent Name",
  XXP2P_SUPPLIER_AGENT_DTLS_AGENT_ADDRESS: "Agent Address",
  XXP2P_SUPPLIER_AGENT_DTLS_BD_PHONE_NUMBER: "Agent Mobile No",
  XXP2P_SUPPLIER_AGENT_DTLS_CONTACT_PERSON_NAME: "Contact Person Name in Agent",
  XXP2P_SUPPLIER_AGENT_DTLS_CONTACT_PERSON_POSITION:
    "Contact Person Position in Agent",
  XXP2P_SUPPLIER_AGENT_DTLS_BD_PERMISSION_NO:
    "Agent Bangladesh Permission No/ Indentor ID",
  XXP2P_SUPPLIER_AGENT_DTLS_AGENT_SINCE_DATE: "Agent Since",
  XXP2P_SUPPLIER_AGENT_DTLS_EMAIL: "Agent Email",
  XXP2P_SUPPLIER_AGENT_DTLS_IRC: "Agent IRC",
  XXP2P_SUPPLIER_AGENT_DTLS_BIN: "Agent BIN",
  XXP2P_SUPPLIER_AGENT_DTLS_TIN_FILE_NAME: "Agent TIN File Name",
  XXP2P_SUPPLIER_AGENT_DTLS_TIN_FILE_ORIGINAL_NAME:
    "Agent TIN Original File Name",
  XXP2P_SUPPLIER_AGENT_DTLS_CREATED_BY: "Agent Details Created By",
  XXP2P_SUPPLIER_AGENT_DTLS_CREATION_DATE: "Agent Creation Date",
  XXP2P_SUPPLIER_AGENT_DTLS_LAST_UPDATED_BY: "Agent Last Update Date",
  XXP2P_SUPPLIER_AGENT_DTLS_LAST_UPDATE_DATE: "Agent Last Update Date",
  XXP2P_SUPPLIER_AGENT_DTLS_ID: "Agent Id",

  XXP2P_REGISTRATION_DECLARATION_ID: "Declaration Id",
  XXP2P_REGISTRATION_DECLARATION_SUPPLIER_ID: "Supplier Id In Declaration",
  XXP2P_REGISTRATION_DECLARATION_AUTHOR_TYPE: "Declaration Authority Type",
  XXP2P_REGISTRATION_DECLARATION_SIGNATURE_FILE_NAME:
    "Signature with Date & Seal File Name",
  XXP2P_REGISTRATION_DECLARATION_SIGNATURE_FILE_ORIGINAL_NAME:
    "Signature with Date & Seal Original File Name",
  XXP2P_REGISTRATION_DECLARATION_COMPANY_SEAL_FILE_NAME:
    "Company Seal File Name",
  XXP2P_REGISTRATION_DECLARATION_COMPANY_SEAL_FILE_ORIGINAL_NAME:
    "Company Seal Original File Name",
  XXP2P_REGISTRATION_DECLARATION_SIGNATORY_NAME: "Name of Signatory",
  XXP2P_REGISTRATION_DECLARATION_IS_AGREED: "Agree",
  XXP2P_REGISTRATION_DECLARATION_CREATED_BY: "Declaration Created By",
  XXP2P_REGISTRATION_DECLARATION_CREATION_DATE: "Declaration Created Date",
  XXP2P_REGISTRATION_DECLARATION_LAST_UPDATED_BY: "Declaration last Updated By",
  XXP2P_REGISTRATION_DECLARATION_LAST_UPDATE_DATE: "Declaration Update Date",
  XXP2P_REGISTRATION_DECLARATION_USER_ID: "Declaration User Id",
};

// export default columnNameDescriptionLookup;

export function getDescription(name: string): string {
  // Convert name to uppercase and trim whitespace for case-insensitive matching
  name = name.toUpperCase().trim();

  // Check if the name exists in the lookup table
  if (name in columnNameDescriptionLookup) {
    return columnNameDescriptionLookup[name];
  } else {
    return `Description not found for ${name}`;
  }
}
