// interface Invoice {
//   INV_ID: number;
//   INVOICE_TYPE: string;
//   PO_NUMBER: number;
//   PO_HEADER_ID: string;
//   RFQ_ID: number;
//   CS_ID: number;
//   USER_ID: number;
//   VENDOR_ID: string;
//   INVOICE_DATE: string;
//   GL_DATE: string;
//   TOTAL_AMOUNT: number;
//   INVOICE_NUM: string;
//   EBS_INVOICE_ID: string;
//   ORG_ID: number;
//   ORGANIZATION_ID: string;
//   INVOICE_STATUS: string;
//   APPROVAL_STATUS: string;
//   TEMPLATE_ID: number;
//   TEMPLATE_STAGE_LEVEL: number;
//   SITE_ID: number;
//   BANK_ID: number;
//   CURRENCY_CODE: string;
//   CREATION_DATE: string;
//   CREATED_BY: number;
//   LAST_UPDATED_BY: string;
//   LAST_UPDATE_DATE: string;
//   SUPPLIER_ID: number;
//   SUPPLIER_FULL_NAME: string;
//   SUPPLIER_USER_NAME: string;
//   ORGANIZATION_NAME: string;
//   EMAIL_ADDRESS: string;
//   PROFILE_PIC1_FILE_NAME: string;
//   PROFILE_PIC2_FILE_NAME: string;
//   ORG_NAME: string;
//   CURRENCY_NAME: string;
//   MODULE_ID: number;
//   STAGE_ID: number;
//   STAGE_LEVEL: number;
//   STAGE_SEQ: number;
//   IS_MUST_APPROVE: number;
//   PAYMENT_METHOD_CODE: string;
// }

interface BuyerStatus {
  APPROVER_FULL_NAME: string;
  ACTION_CODE: number;
  ACTION_DATE: string;
  NOTE: string;
  PROPIC_FILE_NAME: string;
}

interface BankDetails {
  ID: number;
  VENDOR_ID: number;
  ACCOUNT_NAME: string;
  ACCOUNT_NUMBER: string;
  BANK_NAME: string;
  BANK_PARTY_ID: number;
  BRANCH_NAME: string;
  BRANCH_PARTY_ID: number;
  ROUTING_SWIFT_CODE: string;
  SWIFT_CODE: string;
  SITE_ID: string;
  CHEQUE_FILE_NAME: string;
  CHEQUE_FILE_ORIGINAL_NAME: string;
  USER_ID: number;
  ACTIVE_STATUS: string;
  START_DATE: string;
  END_DATE: string;
  CREATED_BY: string;
  CREATION_DATE: string;
  LAST_UPDATED_BY: number;
  LAST_UPDATE_DATE: string;
  CURRENCY_CODE: string;
  MULTI_CURRENCY_ALLOWED_FLAG: string;
  PAYMENT_MULTI_CURRENCY_FLAG: string;
  EBS_UPLOAD: string;
  BANK_ACCT_ID: string;
}

interface Invoice {
  INV_ID: number;
  INVOICE_TYPE: string;
  PO_NUMBER: number;
  PO_HEADER_ID: string;
  RFQ_ID: number;
  CS_ID: string;
  USER_ID: number;
  VENDOR_ID: number;
  INVOICE_DATE: string;
  GL_DATE: string;
  TOTAL_AMOUNT: number;
  INVOICE_NUM: string;
  EBS_INVOICE_ID: string;
  ORG_ID: number;
  ORGANIZATION_ID: string;
  INVOICE_STATUS: string;
  APPROVAL_STATUS: string;
  TEMPLATE_ID: number;
  TEMPLATE_STAGE_LEVEL: number;
  SITE_ID: number;
  BANK_ID: number;
  CURRENCY_CODE: string;
  CREATION_DATE: string;
  CREATED_BY: number;
  LAST_UPDATED_BY: string;
  LAST_UPDATE_DATE: string;
  VENDOR_SITE_ID: number;
  DESCRIPTION: string;
  SOURCE: string;
  PAYMENT_METHOD_CODE: string;
  TERMS_ID: number;
  TERMS_NAME: string;
  EXCHANGE_RATE_TYPE: string;
  EXCHANGE_DATE: string;
  EXCHANGE_RATE: string;
  INVOICE_CREATION_DATE: string;
  STATUS: string;
  FEEDBACK: string;
  LAST_PROCESSED_DATETIME: string;
  ACCT_PAY_CONCATENATED: string;
  MUSHOK_FILE_NAME: string;
  MUSHOK_FILE_ORG_NAME: string;
  INVOICE_INCLUDES_PREPAY_FLAG: string;
  APPLY_PREPAY_NUM: string;
  PREPAY_LINE_NUM: string;
  PREPAY_APPLY_AMOUNT: string;
  PREPAY_GL_DATE: string;
  EBS_PAYMENT_STATUS: string;
  EBS_PAYMENT_AMOUNT: string;
  EBS_PAYMENT_DATE: string;
  PREPAY_ADJUSTED_AMOUNT: string;
  PREPAY_AVAILABLE_AMOUNT: string;
  EBS_INVOICE_STATUS: string;
  SCHEDULE_SYNC_DATETIME: string;
  PREPAY_APP_TOTAL: string;
  CASH_OR_BANK_PAYMENT: string;
  BUYER_USER_ID: number;
  BUYER_APPROVAL_STATUS: string;
  EBS_APPROVAL_STATUS: string;
  UNPAID_AMOUNT: string;
  LC_NUMBER: string;
  BL_NUMBER: string;
  BENEFICIARY_NUMBER: string;
  APPROVAL_FLOW_TYPE: string;
  BUYER_DEPARTMENT: string;
  SUPPLIER_ID: number;
  SUPPLIER_FULL_NAME: string;
  SUPPLIER_USER_NAME: string;
  ORGANIZATION_NAME: string;
  EMAIL_ADDRESS: string;
  PROFILE_PIC1_FILE_NAME: string;
  PROFILE_PIC2_FILE_NAME: string;
  ORG_NAME: string;
  SHIP_TO_LOCATION_NAME: string;
  CURRENCY_NAME: string;
  BUYER: string;
  LE_NAME: string;
  LE_ADDRESS: string;
  LE_BIN: string;
  BUYER_STATUS: BuyerStatus;
  BANK_DETAILS: BankDetails;
  RATE_TYPE: string;
  RATE_DATE: string;
  CONVERSION_RATE: string;
}

export default Invoice;
