let pendingProfileNewInfoAdd = async (
  APPROVER_ID,
  APPROVAL_STATUS,
  SEARCH_VALUE
) => {
  let query = `
    SELECT
  US.USER_ID AS SUPPLIER_ID,
  US.FULL_NAME AS SUPPLIER_FULL_NAME,
  US.USER_NAME AS SUPPLIER_USER_NAME,
  BSC.ORGANIZATION_NAME,
  US.EMAIL_ADDRESS,
  US.NEW_INFO_STATUS AS APPROVAL_STATUS,
  US.PROFILE_NEW_INFO_UID,
  AM.MODULE_ID,
  SA.STAGE_ID,
  SA.STAGE_LEVEL,
  SA.STAGE_SEQ,
  SA.IS_MUST_APPROVE,
  US.INITIATOR_ID,
  'N' AS IS_INITIATOR
  FROM
  XXP2P.XXP2P_STAGE_APPROVERS SA,
  XXP2P.XXP2P_APPROVAL_STAGES XAS,
  XXP2P.XXP2P_APPROVAL_MODULE AM,
  XXP2P.XXP2P_USER US,
  XXP2P.XXP2P_SUPPLIER_BSC_INFO BSC

  WHERE SA.USER_ID = :APPROVER_ID
  AND XAS.MODULE_TYPE_ID = AM.MODULE_ID
  AND LOWER(AM.MODULE_NAME) = LOWER('Profile Update')
  AND US.NEW_INFO_TEMPLATE_ID = SA.STAGE_ID
  AND US.NEW_INFO_STAGE_LEVEL = SA.STAGE_LEVEL
  AND US.NEW_INFO_STATUS = NVL(:APPROVAL_STATUS,US.NEW_INFO_STATUS)
  AND US.NEW_INFO_INITIATOR_STATUS = 'APPROVED'
  AND BSC.USER_ID = US.USER_ID
  AND (
    LOWER(us.USER_NAME) LIKE '%' || LOWER(NVL(:SEARCH_VALUE, us.USER_NAME)) || '%'
    OR LOWER(bsc.ORGANIZATION_NAME) LIKE '%' || LOWER(NVL(:SEARCH_VALUE, bsc.ORGANIZATION_NAME)) || '%'
    OR LOWER(us.EMAIL_ADDRESS) LIKE '%' || LOWER(NVL(:SEARCH_VALUE, us.EMAIL_ADDRESS)) || '%'
)
    ORDER BY US.LAST_UPDATE_DATE DESC
    `;
  return query;
};

let pendingProfileNewInfoAddTotal = async (
  APPROVER_ID,
  APPROVAL_STATUS,
  SEARCH_VALUE
) => {
  let query = `
    SELECT
  COUNT(US.USER_ID) AS TOTAL
  FROM
  XXP2P.XXP2P_STAGE_APPROVERS SA,
  XXP2P.XXP2P_APPROVAL_STAGES XAS,
  XXP2P.XXP2P_APPROVAL_MODULE AM,
  XXP2P.XXP2P_USER US,
  XXP2P.XXP2P_SUPPLIER_BSC_INFO BSC

  WHERE SA.USER_ID = :APPROVER_ID
  AND XAS.MODULE_TYPE_ID = AM.MODULE_ID
  AND LOWER(AM.MODULE_NAME) = LOWER('Profile Update')
  AND US.NEW_INFO_TEMPLATE_ID = SA.STAGE_ID
  AND US.NEW_INFO_STAGE_LEVEL = SA.STAGE_LEVEL
  AND US.NEW_INFO_STATUS = NVL(:APPROVAL_STATUS,US.NEW_INFO_STATUS)
  AND US.NEW_INFO_INITIATOR_STATUS = 'APPROVED'
  AND BSC.USER_ID = US.USER_ID
  AND (
    LOWER(us.USER_NAME) LIKE '%' || LOWER(NVL(:SEARCH_VALUE, us.USER_NAME)) || '%'
    OR LOWER(bsc.ORGANIZATION_NAME) LIKE '%' || LOWER(NVL(:SEARCH_VALUE, bsc.ORGANIZATION_NAME)) || '%'
    OR LOWER(us.EMAIL_ADDRESS) LIKE '%' || LOWER(NVL(:SEARCH_VALUE, us.EMAIL_ADDRESS)) || '%'
)
    `;
    console.log(query);
  return query;
};


let pendingProfileNewInfoAddInitiator = async (
  APPROVER_ID,
  APPROVAL_STATUS,
  SEARCH_VALUE
) => {
  let query = `
    SELECT
  US.USER_ID AS SUPPLIER_ID,
    US.FULL_NAME AS SUPPLIER_FULL_NAME,
    US.USER_NAME AS SUPPLIER_USER_NAME,
    BSC.ORGANIZATION_NAME,
    US.EMAIL_ADDRESS,
    US.NEW_INFO_STATUS AS APPROVAL_STATUS,
    US.NEW_INFO_TEMPLATE_ID AS STAGE_ID,
    US.NEW_INFO_STAGE_LEVEL AS STAGE_LEVEL,
    1 AS STAGE_SEQ,
    0 AS IS_MUST_APPROVE,
    US.PROFILE_NEW_INFO_UID,
    US.INITIATOR_ID,
    'Y' AS IS_INITIATOR
  FROM
  XXP2P.XXP2P_USER US,
  XXP2P.XXP2P_SUPPLIER_BSC_INFO BSC

 WHERE US.INITIATOR_ID = :APPROVER_ID
    AND US.NEW_INFO_INITIATOR_STATUS = NVL(:APPROVAL_STATUS,US.INITIATOR_STATUS)
    AND US.NEW_INFO_STATUS = 'IN PROCESS'
    AND SUBMISSION_STATUS = 'SUBMIT'
    AND BSC.USER_ID = US.USER_ID
  AND (
    LOWER(us.USER_NAME) LIKE '%' || LOWER(NVL(:SEARCH_VALUE, us.USER_NAME)) || '%'
    OR LOWER(bsc.ORGANIZATION_NAME) LIKE '%' || LOWER(NVL(:SEARCH_VALUE, bsc.ORGANIZATION_NAME)) || '%'
    OR LOWER(us.EMAIL_ADDRESS) LIKE '%' || LOWER(NVL(:SEARCH_VALUE, us.EMAIL_ADDRESS)) || '%'
)
    ORDER BY US.LAST_UPDATE_DATE DESC
    `;
  return query;
};

let pendingProfileNewInfoAddTotalInitiator = async (
  APPROVER_ID,
  APPROVAL_STATUS,
  SEARCH_VALUE
) => {
  let query = `
    SELECT
  COUNT(US.USER_ID) TOTAL
  FROM
  XXP2P.XXP2P_USER US,
  XXP2P.XXP2P_SUPPLIER_BSC_INFO BSC

 WHERE US.INITIATOR_ID = :APPROVER_ID
    AND US.NEW_INFO_INITIATOR_STATUS = NVL(:APPROVAL_STATUS,US.INITIATOR_STATUS)
    AND US.NEW_INFO_STATUS = 'IN PROCESS'
    AND SUBMISSION_STATUS = 'SUBMIT'
    AND BSC.USER_ID = US.USER_ID
  AND (
    LOWER(us.USER_NAME) LIKE '%' || LOWER(NVL(:SEARCH_VALUE, us.USER_NAME)) || '%'
    OR LOWER(bsc.ORGANIZATION_NAME) LIKE '%' || LOWER(NVL(:SEARCH_VALUE, bsc.ORGANIZATION_NAME)) || '%'
    OR LOWER(us.EMAIL_ADDRESS) LIKE '%' || LOWER(NVL(:SEARCH_VALUE, us.EMAIL_ADDRESS)) || '%'
)
    `;
    console.log(query);
  return query;
};

let pendingProfileNewInfoAddDetails = async (SUPPLIER_ID, APPROVAL_STATUS) => {
  console.log(SUPPLIER_ID);
  console.log(APPROVAL_STATUS);
  let query = `
    select *
    from  xxp2p.xxp2p_new_info_log 
    WHERE APPROVER_STATUS = NVL('${APPROVAL_STATUS}',APPROVER_STATUS)
    AND ACTION_TAKEN_BY = NVL('${SUPPLIER_ID}',ACTION_TAKEN_BY)
    `;
  console.log(query);
  return query;
};
let tableDetails = async (SUPPLIER_ID, TABLE_NAME, ID, STATUS) => {
  let query = `
    select *
    from  xxp2p.${TABLE_NAME} 
    WHERE ID = '${ID}'
    AND USER_ID = '${SUPPLIER_ID}'
    AND ACTIVE_STATUS = '${STATUS}'
    `;
  //console.log(query);
  return query;
};

module.exports = {
  pendingProfileNewInfoAdd,
  pendingProfileNewInfoAddTotal,
  pendingProfileNewInfoAddDetails,
  tableDetails,
  pendingProfileNewInfoAddInitiator,
  pendingProfileNewInfoAddTotalInitiator,
  
};
